{% set development = development|default(false) %}
version: '3'

services:
  {{ serviceName }}:
    image: redis:{{ image.tag }}
    command: redis-server {% if usePassword %}--requirepass {{ password }}{% endif %}
    {% if persistence.enabled %}
    volumes:
      - {{ serviceName }}_data:/data
    {% endif %}
    deploy:
      mode: replicated
      replicas: 1
      {% if not development %}
      placement:
        constraints:
          - node.role == worker
      {% endif %}
      {% if resources.enabled %}
      resources:
        limits:
          memory: {{ resources.memory }}
          cpus: {{ resources.cpus }}
      {% endif %}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: {{ healthcheck.interval }}
      timeout: {{ healthcheck.timeout }}

  {% if metrics.enabled %}
  {{ serviceName }}_exporter:
    image: oliver006/redis_exporter:latest
    environment:
      REDIS_ADDR: redis://{% if usePassword %}:{{ password }}@{% endif %}{{ serviceName }}:6379
    depends_on:
      - {{ serviceName }}
    networks:
      - {{ metrics.network }}
    deploy:
      mode: replicated
      replicas: 1
      {% if not development %}
      placement:
        constraints:
          - node.role == worker
      {% endif %}
  {% endif %}

{% if persistence.enabled %}
volumes:
  {{ serviceName }}_data:
    driver: {{ persistence.driver }}
    {% if persistence.driver == 'rbd' %}
    driver_opts:
      size: {{ persistence.size }}
    {% endif %}
{% endif %}

{% if metrics.enabled %}
networks:
  {{ metrics.network }}:
    external: true
{% endif %}
