serviceName: redis

image:
  tag: 6

usePassword: false
password: null

healthcheck:
  interval: 60s
  timeout: 20s

resources:
  enabled: false
  memory: 512M
  cpus: 0.5

persistence:
  enabled: false
  driver: local
  size: 1024

metrics:
  enabled: false
  network: prometheus_net


